- hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - name: Display first val
   debug:
     msg: "{{http_port}}"
  - name: Display second value
    debug:
     msg: "{{server_name}}"

     #to run the ansible playbook commands
     #ansible-playbook -e "@vars.yaml" var_file_demo.yaml